plugins {
    id 'com.android.library'
}

allprojects {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

group 'com.w3conext.jailbreak_root_detection'

android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.w3conext.jailbreak_root_detection'
    }

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    implementation "androidx.annotation:annotation:1.9.1"
    implementation 'com.scottyab:rootbeer-lib:0.1.1'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
}
